### ISSUE TITLE
Setup for OSCD and compatibility to SeCo repository

### ISSUE THREAD

**Issue by pvmilk** [utkarshmall13/CACo#4]
Nice work on the paper and thank you for making the source code/ pretrained model public. 

I am trying to recreate the result on the paper on change detection. 
The paper mentioned that the model architecture of this work on OSCD data followed SeCo paper. 
I would like to know whether the pretrained models are compatible with the [main_oscd.py](https://github.com/ServiceNow/seasonal-contrast/blob/main/main_oscd.py) on SeCo repository.
- It seems that moco2_module.py of SeCo and CACo are difference. Is it meant that to use CACo pretrained model, I simple have to load the model using moco2_module.py from CACO, and copy it backbone with the following code and use the SeCo main_oscd.py? Or since we only use MocoV2 code to load the backbone, can I use moco2_module.py from SeCo to load CACo pretrained model also?
```
model = MocoV2.load_from_checkpoint(model_path)
backbone = deepcopy(model.encoder_q)
```
- SeCo main_oscd.py seems to report only result on resnet-18, but in your paper both on resnet-18 and resnet-50. Any modification on the  SeCo main_oscd.py source code?

Thank you.

**Comment by utkarshmall13** [comment]
Hi, yes the model should be compatible with the main_oscd.py. You can also check the models/checkpoints without the lightning wrapper [here](https://research.cs.cornell.edu/caco/checkpoints/) and refer to this [notebook](https://github.com/utkarshmall13/CACo/blob/main/notebooks/eurosat_eval_pytorch.ipynb) for model loading instructions.
We did not make any changes to the inference and testing code of main_oscd.py. However since the training data is different between seco and CACo, we recommend using the retrained [seco checkpoint](https://research.cs.cornell.edu/caco/checkpoints/) for a fair comparison.

**Comment by pvmilk** [comment]
@utkarshmall13 Thanks for your reply. 

I did try to use main_oscd.py with CACo pretrained weight (using the method provided in the notebook without pl wrapper). However, I cannot recreate the result (actually the result seems to be worse than seco; both from this paper and the original paper).

I would like to know a few configurations.
- main_oscd.py fixed the seeding to 42. In your experiment, is it the same?
- main_oscd.py by default, trained for 100 epochs and use the last model. Does it same in your case?
- main_oscd.py didn't really provide the test code. Does the reported values in the paper are from the validation during training? or do you have a separate code for testing?
